name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          user: TadeyRuk
          token: ${{ secrets.GITHUB_TOKEN }}

          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
