name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: TadeyRuk
          token: ${{ secrets.SECRET_RUKKAN }}

          config_timezone: Asia/Manila

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_pagespeed: yes
          plugin_pagespeed_detailed: no
          plugin_pagespeed_url: https://portfolio-web-seven-steel.vercel.app
          plugin_pagespeed_screenshot: no

          plugin_habits: yes
          plugin_habits_charts_type: bars
          plugin_habits_days: 61
          plugin_habits_facts: yes
          plugin_habits_from: 100

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size

          plugin_topics: yes
          plugin_topics_limit: 8
          plugin_topics_mode: icons

          plugin_projects: yes
